"""auto update

Revision ID: 14c60c6d7f70
Revises: 44229b7f8b43
Create Date: 2026-01-29 02:01:38.628780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c60c6d7f70'
down_revision: Union[str, Sequence[str], None] = '44229b7f8b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_caves_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('provincia', sa.String(), nullable=False),
    sa.Column('materiale', sa.String(), nullable=False),
    sa.Column('numero_cave', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_caves_data_id'), 'active_caves_data', ['id'], unique=False)
    op.create_table('competitor_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('provincia', sa.String(), nullable=False),
    sa.Column('materiale', sa.String(), nullable=False),
    sa.Column('tipo_concorrente', sa.String(), nullable=False),
    sa.Column('numero_concorrenti', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_data_id'), 'competitor_data', ['id'], unique=False)
    op.create_table('destination_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('provincia', sa.String(), nullable=False),
    sa.Column('materiale', sa.String(), nullable=False),
    sa.Column('destinazione_tipo', sa.String(), nullable=False),
    sa.Column('destinazione_dettaglio', sa.String(), nullable=True),
    sa.Column('volume_m3', sa.Float(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destination_data_id'), 'destination_data', ['id'], unique=False)
    op.create_table('economic_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('provincia', sa.String(), nullable=False),
    sa.Column('materiale', sa.String(), nullable=False),
    sa.Column('fatturato', sa.Float(), nullable=False),
    sa.Column('costi', sa.Float(), nullable=False),
    sa.Column('utile_lordo', sa.Float(), nullable=False),
    sa.Column('utile_netto', sa.Float(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_data_id'), 'economic_data', ['id'], unique=False)
    op.create_table('employment_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('provincia', sa.String(), nullable=False),
    sa.Column('materiale', sa.String(), nullable=False),
    sa.Column('numero_occupati', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employment_data_id'), 'employment_data', ['id'], unique=False)
    op.create_table('extraction_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('provincia', sa.String(), nullable=False),
    sa.Column('materiale', sa.String(), nullable=False),
    sa.Column('volume_m3', sa.Float(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_data_id'), 'extraction_data', ['id'], unique=False)
    op.create_table('price_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('classe_materiale', sa.String(), nullable=False),
    sa.Column('prezzo_euro_m3', sa.Float(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_data_id'), 'price_data', ['id'], unique=False)
    op.create_table('sales_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('provincia', sa.String(), nullable=False),
    sa.Column('materiale', sa.String(), nullable=False),
    sa.Column('volume_m3', sa.Float(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_data_id'), 'sales_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_data_id'), table_name='sales_data')
    op.drop_table('sales_data')
    op.drop_index(op.f('ix_price_data_id'), table_name='price_data')
    op.drop_table('price_data')
    op.drop_index(op.f('ix_extraction_data_id'), table_name='extraction_data')
    op.drop_table('extraction_data')
    op.drop_index(op.f('ix_employment_data_id'), table_name='employment_data')
    op.drop_table('employment_data')
    op.drop_index(op.f('ix_economic_data_id'), table_name='economic_data')
    op.drop_table('economic_data')
    op.drop_index(op.f('ix_destination_data_id'), table_name='destination_data')
    op.drop_table('destination_data')
    op.drop_index(op.f('ix_competitor_data_id'), table_name='competitor_data')
    op.drop_table('competitor_data')
    op.drop_index(op.f('ix_active_caves_data_id'), table_name='active_caves_data')
    op.drop_table('active_caves_data')
    # ### end Alembic commands ###