"""auto update

Revision ID: 44229b7f8b43
Revises: 634756e3a701
Create Date: 2026-01-22 08:53:40.084856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44229b7f8b43'
down_revision: Union[str, Sequence[str], None] = '634756e3a701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('province_material_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('provincia', sa.String(), nullable=False),
    sa.Column('materiale', sa.String(), nullable=False),
    sa.Column('numero_cave', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_province_material_data_id'), 'province_material_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_province_material_data_id'), table_name='province_material_data')
    op.drop_table('province_material_data')
    # ### end Alembic commands ###