"""auto update

Revision ID: 634756e3a701
Revises: 
Create Date: 2026-01-22 07:54:13.144158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634756e3a701'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annual_cave_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('numero_cave', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annual_cave_data_id'), 'annual_cave_data', ['id'], unique=False)
    op.create_table('cave_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('numero_fascicolo', sa.String(), nullable=True),
    sa.Column('azienda', sa.String(), nullable=True),
    sa.Column('localita', sa.String(), nullable=True),
    sa.Column('comune', sa.String(), nullable=True),
    sa.Column('provincia', sa.String(), nullable=True),
    sa.Column('dati_catastali', sa.String(), nullable=True),
    sa.Column('stato_cava', sa.String(), nullable=True),
    sa.Column('aperta_fino_al', sa.Integer(), nullable=True),
    sa.Column('materiale', sa.String(), nullable=True),
    sa.Column('numero_decreto', sa.String(), nullable=True),
    sa.Column('data_decreto', sa.String(), nullable=True),
    sa.Column('scadenza_autorizzazione', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cave_details_id'), 'cave_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cave_details_id'), table_name='cave_details')
    op.drop_table('cave_details')
    op.drop_index(op.f('ix_annual_cave_data_id'), table_name='annual_cave_data')
    op.drop_table('annual_cave_data')
    # ### end Alembic commands ###